[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "galileo_python"
author = "Galileo Technologies, Inc"
author-email = "team@rungalileo.io"
home-page = "https://www.github.com/rungalileo/galileo_python"
description-file = "README.md"
requires-python = ">=3.7"
requires = [
    "pydantic",
    "torch",
    "keras",
    "tensorflow",
    "pytorch-lightning",
]

[tool.flit.metadata.urls]
Documentation = "https://www.github.com/rungalileo/galileo_python/docs"

[tool.flit.metadata.requires-extra]
test = [
    "pytest >=5.2",
    "mypy >=0.812",
    "coverage >=5.5",
    "pytest-cov >=2.11.1"
]
dev = [
    "flake8 >=3.8.4",
    "black >=20.8b1",
    "isort >=5.8.0",
    "autoflake >=1.4"
]

[tool.isort]
profile = "black"
